//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJBCS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string AttendanceID { get; set; }
        public System.DateTime TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string StudentID { get; set; }
        public bool IsNotified { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
