//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJBCS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistributionList()
        {
            this.RelDistributionLists = new HashSet<RelDistributionList>();
        }
    
        public System.Guid DistributionListID { get; set; }
        public string DistributionListName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelDistributionList> RelDistributionLists { get; set; }
    }
}
