//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJBCS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelDistributionList
    {
        public System.Guid RelDistributionListID { get; set; }
        public string StudentID { get; set; }
        public System.Guid DistributionListID { get; set; }
    
        public virtual DistributionList DistributionList { get; set; }
        public virtual Student Student { get; set; }
    }
}
