//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJBCS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public System.Guid AttendanceID { get; set; }
        public System.DateTime TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public System.Guid StudentID { get; set; }
        public string TimeInID { get; set; }
        public string TimeOutID { get; set; }
        public Nullable<bool> TimeInNotified { get; set; }
        public Nullable<bool> TimeOutNotified { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
