//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJBCS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelOrganization
    {
        public System.Guid RelOrganizationID { get; set; }
        public System.Guid StudentID { get; set; }
        public System.Guid OrganizationID { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Student Student { get; set; }
    }
}
